### PR TITLE
Update to ADLS Gen1 storage class

### PR DESCRIPTION
**Pull request by dremioJonny**
The storage class currently in the helm chart for ADLS Gen1 is incorrect in the core-site.xml and dremio.conf, as per https://docs.dremio.com/deployment/dist-store-config.html. An update has been added to cater for pre-3.2.0 releases where adl:// was the correct connection to Gen1 storage, as well as the new dremioAdl:// format.

### CODE REVIEW

**Comment by PeeGey** [comment]
@dremioJonny i'm not able to start the dremio install on my azure k8s cluster. Any chance you can help me with the error?

**Comment by dremioJonny** [comment]
@PeeGey, what issue are you currently experiencing? Do the Dremio pods deploy? Also, for the distributed storage are you using ADLS Gen1 or Gen2 and are you using service account or the storage account access key?

**Comment by PeeGey** [comment]
Hey Jonny,

Probably i didn't post on a proper place, since i was just trying to get in
touch with some of the developers of the dremio cloud tools
I used the helm installation on a K8s clust in the azure cloud. The cluster
i'm using has the Standard_D4s_v3 with 4 nodes.

I'm able to install it with 0 coordinators (only the master), 2 executors
and keeping the 3 zookeepers.
But every time i try a different combination, like 3 executors, or 2
coordinators and 2 executors, it always fail. It should be possible right?

**Comment by dremioJonny** [comment]
When you say it fails, are you seeing pods in "Pending", "CrashLoopBackOff" or some other error. If you "run kubectl describe pods ...<name of failed pod>" what are you seeing at the bottom of the description? The name of the of the pods will be something like dremio-executor-1.

**Comment by dremioJonny** [comment]
Also, to add, there's really good support at https://community.dremio.com/ who will be able to help you also. I would say that we should also look to log your issue there to continue the conversation.

**Comment by dremioJonny** [comment]
Closing and re-raising PR to only be relevant changes.

**Pull request closed without merging**
